CREATE DATABASE IF NOT EXISTS todo_app;
USE todo_app;

CREATE TABLE usuarios (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  username VARCHAR(55) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tareas (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  titulo VARCHAR(255) NOT NULL,
  descripcion TEXT,
  completada BOOLEAN DEFAULT FALSE,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  fecha_limite DATE NULL,
  usuario_id CHAR(36) NOT NULL,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
